apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: "tiltak-auditlogger"
  namespace: "team-tiltak"
  labels:
    "team": "team-tiltak"
spec:
  gcp:
    sqlInstances:
      - type: POSTGRES_17
        tier: {{db-tier}}
        cascadingDelete: false
        highAvailability: false
        diskAutoresize: true
        diskAutoresizeLimit: 60
        databases:
          - name: tiltak-auditlogger
            envVarPrefix: DB
  env:
    - name: MILJO
      value: {{miljo}}
  kafka:
    pool: {{kafka-pool}}
  image: {{image}}
  port: 8080
  liveness:
    path: /internal/health/liveness
    initialDelay: 30
    timeout: 1
    periodSeconds: 30
    failureThreshold: 10
  readiness:
    path: /internal/health/readiness
    initialDelay: 30
    timeout: 1
    periodSeconds: 30
    failureThreshold: 10
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 50
  resources:
    limits:
      cpu: "200m"
      memory: "256Mi"
    requests:
      cpu: "200m"
      memory: "256Mi"