apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: "tiltak-auditlogger"
  namespace: "team-tiltak"
  labels:
    "team": "team-tiltak"
spec:
  kafka:
    pool: {{kafka-pool}}
  image: {{image}}
  liveness:
    path: "/internal/isAlive"
    port: 8092
    initialDelay: 20
    timeout: 60
  readiness:
    path: "/internal/isReady"
    port: 8092
    initialDelay: 20
    timeout: 60
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 50
  resources:
    limits:
      cpu: "200m"
      memory: "256Mi"
    requests:
      cpu: "200m"
      memory: "256Mi"